title: Math Example Site
description: Example site demonstrating Jekyll Maths LaTeX to Image plugin

baseurl: ""
url: ""

plugins:
  - jekyll-maths-latex-to-image

jekyll-maths-latex-to-image:
  enabled: true              # Enable/disable the plugin
  path: /assets/img/math     # Path for generated images
  format: both              # 'svg', 'png', or 'both'
