title: Math Example Site
description: Example site demonstrating Jekyll Maths LaTeX to Image plugin

baseurl: ""
url: ""

plugins:
  - jekyll-maths-latex-to-image

texsvg_math_renderer:
  path: /assets/img/math
  format: both
